<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>log</string>
		<string>saslog</string>
	</array>
	<key>name</key>
	<string>SAS Log</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.SASLog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.column.SASLog</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>NOTE line</string>
			<key>match</key>
			<string>(?i:^(NOTE)(\:)\s*(.*))</string>
			<key>name</key>
			<string>meta.note.SASLog</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.SASLog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parenthesis.open.SASLog</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.other.SASLog</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parenthesis.close.SASLog</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.column.SASLog</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>MLOGIC message</string>
			<key>match</key>
			<string>(?i:^(MLOGIC)(\()(\w*)(\))(\:)\s*(.*))</string>
			<key>name</key>
			<string>meta.mlogic.SASLog</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.SASLog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parenthesis.open.SASLog</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.other.SASLog</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parenthesis.close.SASLog</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.column.SASLog</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>source.sas</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>MPRINT message</string>
			<key>match</key>
			<string>(?i:^(MPRINT)(\()(\w*)(\))(\:)\s*(.*))</string>
			<key>name</key>
			<string>meta.mprint.SASLog</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.SASLog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parenthesis.open.SASLog</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.other.SASLog</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parenthesis.close.SASLog</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.column.SASLog</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>source.sas</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>MACROGEN message</string>
			<key>match</key>
			<string>(?i:^(MACROGEN)(\()(\w*)(\))(\:)\s*(.*))</string>
			<key>name</key>
			<string>meta.macrogen.SASLog</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.SASLog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.column.SASLog</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>SYMBOLGEN message</string>
			<key>match</key>
			<string>(?i:^(SYMBOLGEN)(\:)\s(\w*))</string>
			<key>name</key>
			<string>meta.symbolgen.SASLog</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.macro.SASLog</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>macro variable</string>
			<key>match</key>
			<string>(?i:(macro)\s(\w*))</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>number.line.source.sas</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>source.sas</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>source sas</string>
			<key>match</key>
			<string>(?i:^(\d+)(.*))</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Error line</string>
			<key>match</key>
			<string>(?i:^(ERROR|ERREUR|WARNING|ATTENTION)|Uninitialized| remerg|invalid).*</string>
			<key>name</key>
			<string>invalid.SASLog</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Info message</string>
			<key>match</key>
			<string>(?i:^INFO).*</string>
			<key>name</key>
			<string>entity.name.function.SASLog</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.SASLog</string>
	<key>uuid</key>
	<string>129969b6-3952-4444-ba64-36b83199a78b</string>
</dict>
</plist>
